parameters:
  componentDetection: 'false'
  testLogTitle: 'Non-Windows'
  enableADOLogIssue: 'false'

steps:

- ${{ if eq(parameters.componentDetection, 'true') }}:
    # Component detection
    - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
      displayName: 'Component Detection'
      condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))

# Clean
- checkout: self
  clean: true

- script: |
    git config user.email "azure-pipelines-bot@microsoft.com"
    git config user.name "azure-pipelines-bot"
    git checkout -f origin/releases/$(version)
  displayName: Checkout release branch
  condition: and(ne(variables['version'], ''), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

# Build agent layout
- script: ./dev.sh layout Release
  workingDirectory: src
  displayName: Build & Layout Release
  env:
    ADO_ENABLE_LOGISSUE: ${{ parameters.enableADOLogIssue }}
